### ISSUE TITLE
Network aka UDPBD

### ISSUE THREAD

**Issue by binarygeek119** [sync-on-luma/xebplus-neutrino-loader-plugin#10]
This would work for fat and slim.

**Comment by MegaBitmap** [comment]
Network loading is fully functional in my fork: https://github.com/MegaBitmap/UDPBD-for-XEBP
I have added the necessary changes for this repository here: https://github.com/sync-on-luma/xebplus-neutrino-loader-plugin/commit/88ea5e524c34faae23e8ed95db9cd92e3f81e6c6
These changes have not been added to main/releases.

**Comment by Windows10User2** [comment]
> Network loading is fully functional in my fork: https://github.com/MegaBitmap/UDPBD-for-XEBP I have added the necessary changes for this repository here: [88ea5e5](https://github.com/sync-on-luma/xebplus-neutrino-loader-plugin/commit/88ea5e524c34faae23e8ed95db9cd92e3f81e6c6) These changes have not been added to main/releases.

I ran the mentioned fork by watching [this](https://www.youtube.com/watch?v=AvbIMnbT3dU) video but I had to change wLE_ISR's IP address to 192.168.000.010 like shown on said video because the one I used [192.168.001.010] didn't work and made the mentioned fork close. Also, for some reason, said fork doesn't work if ran from mc1 since it freezes and so I ran it from an USB device. How to know which Neutrino version comes with it and how to update it?

**Comment by MegaBitmap** [comment]
> > Network loading is fully functional in my fork: https://github.com/MegaBitmap/UDPBD-for-XEBP I have added the necessary changes for this repository here: [88ea5e5](https://github.com/sync-on-luma/xebplus-neutrino-loader-plugin/commit/88ea5e524c34faae23e8ed95db9cd92e3f81e6c6) These changes have not been added to main/releases.
> 
> I ran the mentioned fork by watching [this](https://www.youtube.com/watch?v=AvbIMnbT3dU) video but I had to change wLE_ISR's IP address to 192.168.000.010 like shown on said video because the one I used [192.168.001.010] didn't work and made the mentioned fork close. Also, for some reason, said fork doesn't work if ran from mc1 since it freezes and so I ran it from an USB device. How to know which Neutrino version comes with it and how to update it?


Xtreme Elite Boot+ and the neutrinoLauncher plug-in must be installed onto a flash drive, not a memory card. My fork has neutrino v1.3.1 included. If you want to use a different version then replace the neutrino.elf, config, and modules folder in mass:/XEBPLUS/APPS/neutrinoLauncher with whichever version you want to use from https://github.com/rickgaiser/neutrino/releases

**Comment by Windows10User2** [comment]
> > > Network loading is fully functional in my fork: https://github.com/MegaBitmap/UDPBD-for-XEBP I have added the necessary changes for this repository here: [88ea5e5](https://github.com/sync-on-luma/xebplus-neutrino-loader-plugin/commit/88ea5e524c34faae23e8ed95db9cd92e3f81e6c6) These changes have not been added to main/releases.
> > 
> > 
> > I ran the mentioned fork by watching [this](https://www.youtube.com/watch?v=AvbIMnbT3dU) video but I had to change wLE_ISR's IP address to 192.168.000.010 like shown on said video because the one I used [192.168.001.010] didn't work and made the mentioned fork close. Also, for some reason, said fork doesn't work if ran from mc1 since it freezes and so I ran it from an USB device. How to know which Neutrino version comes with it and how to update it?
> 
> Xtreme Elite Boot+ and the neutrinoLauncher plug-in must be installed onto a flash drive, not a memory card. My fork has neutrino v1.3.1 included. If you want to use a different version then replace the neutrino.elf, config, and modules folder in mass:/XEBPLUS/APPS/neutrinoLauncher with whichever version you want to use from https://github.com/rickgaiser/neutrino/releases

Could you add that information refarding the USB device to the repo and the one regarding having to change wLE_ISR's IP address to 192.168.000.010?

Also, do you know the differences between Neutrino 1.3.1 and its development builds?

**Comment by MegaBitmap** [comment]
> Could you add the information regarding having to change wLE_ISR's IP address to 192.168.000.010?

I was not able to reproduce this issue. 
I went through the complete setup process with wLE_ISR's IP address set to 192.168.1.10 and the PC's IP address set to 192.168.1.74. I did not have any issues during the sync process or while playing. 
I went through the setup process again with wLE_ISR's IP address set to 192.168.0.10 and the PC's IP address set to 192.168.0.74.
Again, I did not find any issues. I'm using wLE_isr 311916e on a slim 75001.


> If the original work doesn't support UDPBD unlike yours, then why does it come with its modules?

It's more convenient to include all of the modules. There is plenty of free space on a flash drive.


> Does XEB+ only support ISO like XEB+ neutrino Launcher Plugin?

Only ISOs are supported. The sync app can convert CD-ROM bin/cue to ISO.


> Also, do you know the differences between Neutrino 1.3.1 and its development builds?

Read all the changes between them here: 
https://github.com/rickgaiser/neutrino/compare/v1.3.1...latest

**Comment by Windows10User2** [comment]
> > Could you add the information regarding having to change wLE_ISR's IP address to 192.168.000.010?
> 
> I was not able to reproduce this issue. I went through the complete setup process with wLE_ISR's IP address set to 192.168.1.10 and the PC's IP address set to 192.168.1.74. I did not have any issues during the sync process or while playing. I went through the setup process again with wLE_ISR's IP address set to 192.168.0.10 and the PC's IP address set to 192.168.0.74. Again, I did not find any issues. I'm using wLE_isr 311916e on a slim 75001.
> 
> > If the original work doesn't support UDPBD unlike yours, then why does it come with its modules?
> 
> It's more convenient to include all of the modules. There is plenty of free space on a flash drive.
> 
> > Does XEB+ only support ISO like XEB+ neutrino Launcher Plugin?
> 
> Only ISOs are supported. The sync app can convert CD-ROM bin/cue to ISO.
> 
> > Also, do you know the differences between Neutrino 1.3.1 and its development builds?
> 
> Read all the changes between them here: [rickgaiser/neutrino@v1.3.1...latest](https://github.com/rickgaiser/neutrino/compare/v1.3.1...latest)

I wasn't even able to FTP files from the PC to the PS2 with wLE_ISR's IP address set to 192.168.0.10 using FileZilla. I'm using wLE_ISR 311916e on a 75004.

Also, is wLE_ISR (or any LE/uLE/wLE version)'s IP address the same as the PS2's IP address or are they different things (maybe the latter is only set by the network adaptor set-up disc)?

**Comment by Windows10User2** [comment]
> @Windows10User2 i went through the complete setup process with [wLE_kHn](https://web.archive.org/web/20231103055706/https://cdn.discordapp.com/attachments/652863740370485258/742327866854998116/wLE_kHn_20200810.7z) IP address set to 192.168.0.3 and the PC IP address set to 192.168.0.2. I did not have any issues during the sync process or while playing.
> 
> @MegaBitmap UDPBD-Server doesn't work anymore because the latest version for Windows is still not compiled (more details [here](https://github.com/israpps/udpbd-server/issues/1)). Can you help with this?
> 
> @sync-on-luma is it possible to add custom games location for USB via List Builder GUI (not only in the root of USB)?

If using udpbd-vexfat.exe on OPL UDPBD, what's the command to run the former? If using udpbd-server.exe on OPL UDPBD, it is:

"C:\path\to\udpbd-server.exe" \\.\F:

("F:" is a USB flash drive in this case).

Do I have to format the partition/disk with Linux to run OPL UDPBD if using udpbd-server.exe?

**Comment by sync-on-luma** [comment]
> @sync-on-luma is it possible to add custom games location for USB via List Builder GUI (not only in the root of USB)?

Not possible in the current version, but it wouldn't be hard to change. Why do you need to point to a different directory though? If
 you're loading games from USB the plugin only looks in the root of the drive, and if you're using a different device it won't be looking for the USB list. It's designed the way it is because I can't envision a scenario where you'd need to look in any other location.

**Comment by sync-on-luma** [comment]
Feature has been added in version 2.3

**Comment by Windows10User2** [comment]
UDPBD for XEB+ no longer closes if not using wLE_ISR's 192.168.000.010 IP address. I forgot to edit wLE_ISR's Default Gateway to match my PC's.



> > Why do you need to point to a different directory though?
> 
> I use BDM Prefix Path in OPL so that unnecessary folders are not created in the root of the drive. Please add it to List Builder GUI.

What is the List Builder for?
