### ISSUE TITLE
UDPBD for XEB+ closes if not using wLE_ISR's 192.168.000.010 IP address and so I can't play games via UDPBD if not using it.

### ISSUE THREAD

**Issue by Windows10User2** [sync-on-luma/xebplus-neutrino-loader-plugin#14]
UDPBD for XEB+ closes if not using wLE_ISR's 192.168.000.010 IP address and so I can't play games via UDPBD if not using it. Something might be wrong since I can't even FTP files from the PC to the PS2 using FileZilla and PS2Net if using said IP address.

**Comment by sync-on-luma** [comment]
I'd first make 100% sure that you're using the correct network and subnet. Run `ipconfig` (or `ifconfig` on Linux) in a command prompt on your server, and make sure the first thee values of the PS2's IP address match those in the first entry that is not a localhost or loopback connection. Also make sure the subnet mask matches.

If you're certain you're everything is on the correct network and subent and still have an issue, try changing the last value of the PS2 IP, as there may be an IP conflict.

If that isn't the issue, then, if you're on Windows, make sure Windows Defender / Windows Firewall aren't blocking incoming connections to the server application or filtering the UDPBD port. Also make sure you don't have any other antivirus or network protection software that could be interfering.

If that still doesn't work, log into your router and make sure there are no firewall or port forward settings that could be interfering with the sever. The exact settings you'll want to look for vary by router make and model. 

If, after all that, the issue still persists, I'd post the issue in [this repository](https://github.com/MegaBitmap/UDPBD-for-XEBP), which is maintained by the developer of the UDPBD server software. I had no part in developing the server application, so if it's an actual bug causing this issue there's little I can do to help.

**Comment by Windows10User2** [comment]
> I'd first make 100% sure that you're using the correct network and subnet. Run `ipconfig` (or `ifconfig` on Linux) in a command prompt on your server, and make sure the first thee values of the PS2's IP address match those in the first entry that is not a localhost or loopback connection. Also make sure the subnet mask matches.
> 
> If you're certain you're everything is on the correct network and subent and still have an issue, try changing the last value of the PS2 IP, as there may be an IP conflict.
> 
> If that isn't the issue, then, if you're on Windows, make sure Windows Defender / Windows Firewall aren't blocking incoming connections to the server application or filtering the UDPBD port. Also make sure you don't have any other antivirus or network protection software that could be interfering.
> 
> If that still doesn't work, log into your router and make sure there are no firewall or port forward settings that could be interfering with the sever. The exact settings you'll want to look for vary by router make and model.
> 
> If, after all that, the issue still persists, I'd post the issue in [this repository](https://github.com/MegaBitmap/UDPBD-for-XEBP), which is maintained by the developer of the UDPBD server software. I had no part in developing the server application, so if it's an actual bug causing this issue there's little I can do to help.



> I'd first make 100% sure that you're using the correct network and subnet. Run `ipconfig` (or `ifconfig` on Linux) in a command prompt on your server, and make sure the first thee values of the PS2's IP address match those in the first entry that is not a localhost or loopback connection. Also make sure the subnet mask matches.
> 
> If you're certain you're everything is on the correct network and subent and still have an issue, try changing the last value of the PS2 IP, as there may be an IP conflict.
> 
> If that isn't the issue, then, if you're on Windows, make sure Windows Defender / Windows Firewall aren't blocking incoming connections to the server application or filtering the UDPBD port. Also make sure you don't have any other antivirus or network protection software that could be interfering.
> 
> If that still doesn't work, log into your router and make sure there are no firewall or port forward settings that could be interfering with the sever. The exact settings you'll want to look for vary by router make and model.
> 
> If, after all that, the issue still persists, I'd post the issue in [this repository](https://github.com/MegaBitmap/UDPBD-for-XEBP), which is maintained by the developer of the UDPBD server software. I had no part in developing the server application, so if it's an actual bug causing this issue there's little I can do to help.

I'm certain everything is right on the network and subnet and I still have this issue. Maybe something in my network already uses wLE_ISR's default IP address (192.168.000.010)? If so, how can I know it? Also, is wLE_ISR's IP address the same as the PS2's IP address (which is set by the PS2 Network Adaptor Start-Up disc or by some games which can set it) or they're different things, even though they may share the same IP address?

My PC doesn't even have Windows Defender since I removed it with NTLite and Windows and the router's Firewalls don't stop me from connecting the PC to the PS2 if using another IP address than wLE_ISR's default. I also don't have any other antivirus or network protection software that could be interfering.

I already reported this issue [here](https://github.com/sync-on-luma/xebplus-neutrino-loader-plugin/issues/10#issuecomment-2466767711) (I did it in this repository since his doesn't even have an "Issues" section so I can't even talk about this problem) and the developer answered me [here](https://github.com/sync-on-luma/xebplus-neutrino-loader-plugin/issues/10#issuecomment-2468658739) saying he wasn't able to reproduce this issue.

**Comment by MegaBitmap** [comment]
Do not use leading "0"  
For example 192.168.001.010 is WRONG.  
Instead use 192.168.1.10, This is CORRECT.  
For example 192.168.000.010 is WRONG.  
Instead use 192.168.0.10, This is CORRECT.  

The leading "0" makes Windows think you are using octal numbers instead of regular decimal numbers.

**Comment by Windows10User2** [comment]
> Do not use leading "0" For example 192.168.001.010 is WRONG. Instead use 192.168.1.10, This is CORRECT. For example 192.168.000.010 is WRONG. Instead use 192.168.0.10, This is CORRECT.
> 
> The leading "0" makes Windows think you are using octal numbers instead of regular decimal numbers.

And I don't. I'm talking about wLE_ISR's IP address, not Windows'. On wLE_ISR they appear that way.

**Comment by Windows10User2** [comment]
> @Windows10User2 try [wLE_kHn](https://web.archive.org/web/20231103055706/https://cdn.discordapp.com/attachments/652863740370485258/742327866854998116/wLE_kHn_20200810.7z).

What is the difference between it and wLE_ISR?

**Comment by Windows10User2** [comment]
> @Windows10User2 read [this](https://bitbucket.org/ShaolinAssassin/popstarter-documentation-stuff/wiki/uLE_kHn).

I don't want it. I don't carw about VCDs and wLE_ISR can read exFAT USB devices.

**Comment by Windows10User2** [comment]
> I'd first make 100% sure that you're using the correct network and subnet. Run `ipconfig` (or `ifconfig` on Linux) in a command prompt on your server, and make sure the first thee values of the PS2's IP address match those in the first entry that is not a localhost or loopback connection. Also make sure the subnet mask matches.
> 
> If you're certain you're everything is on the correct network and subent and still have an issue, try changing the last value of the PS2 IP, as there may be an IP conflict.
> 
> If that isn't the issue, then, if you're on Windows, make sure Windows Defender / Windows Firewall aren't blocking incoming connections to the server application or filtering the UDPBD port. Also make sure you don't have any other antivirus or network protection software that could be interfering.
> 
> If that still doesn't work, log into your router and make sure there are no firewall or port forward settings that could be interfering with the sever. The exact settings you'll want to look for vary by router make and model.
> 
> If, after all that, the issue still persists, I'd post the issue in [this repository](https://github.com/MegaBitmap/UDPBD-for-XEBP), which is maintained by the developer of the UDPBD server software. I had no part in developing the server application, so if it's an actual bug causing this issue there's little I can do to help.



> Do not use leading "0" For example 192.168.001.010 is WRONG. Instead use 192.168.1.10, This is CORRECT. For example 192.168.000.010 is WRONG. Instead use 192.168.0.10, This is CORRECT.
> 
> The leading "0" makes Windows think you are using octal numbers instead of regular decimal numbers.

How to use Neutrino's compatibility modes when using XEB+ neutrino Launcher Plugin via UDPBD?

**Comment by sync-on-luma** [comment]
> How to use Neutrino's compatibility modes when using XEB+ neutrino Launcher Plugin via UDPBD?

The same way as any other device. Press SQUARE and select the modes you want from the context menu.

**Comment by Windows10User2** [comment]
> > How to use Neutrino's compatibility modes when using XEB+ neutrino Launcher Plugin via UDPBD?
> 
> The same way as any other device. Press SQUARE and select the modes you want from the context menu.

I never used any modes on Neutrino so I don't know why. Do I have to press Square on "neutrino Launcher (UDPBD)" on XEB+'s interface?

**Comment by sync-on-luma** [comment]
Yes, SQUARE opens the context menu for the currently highlighted game in the list.

**Comment by Windows10User2** [comment]
> Yes, SQUARE opens the context menu for the currently highlighted game in the list.

Does XEB+ neutrino Launcher Plugin always include Neutrino's latest stable version, and if so, does it include its latest commit as well? Also, what's the difference between Neutrino's latest stable versions and latest development builds? Are the latter more compatible with PS2 games or have extra features?

**Comment by Windows10User2** [comment]
UDPBD for XEB+ no longer closes if not using wLE_ISR's 192.168.000.010 IP address. I forgot to edit wLE_ISR's Default Gateway to match my PC's.

**Comment by sync-on-luma** [comment]
> > 
> 
> Does XEB+ neutrino Launcher Plugin always include Neutrino's latest stable version, and if so, does it include its latest commit as well? Also, what's the difference between Neutrino's latest stable versions and latest development builds? Are the latter more compatible with PS2 games or have extra features?

The plugin is designed around the stable build of neutrino and ad such the latest stable release is included. Commits are changes to made to the public source code, but they do not necessarily correspond to a release. GitHub automatically packages the current version of the source code for distribution with each release at the time it is created. This way the source paired with each release will (at least in theory) result in the same binary as what's pre-compiled in the release.
The neutrino development build is compiled from the current version of the source code every time there's a change in the codebase. These releases can happen as often as once per day and undergo minimal testing, if any. This is far too unstable to build a front-end around. 

> What is the List Builder for?

The list builder is used to generate the game lists required by the HDD, USB, and MX4SIO loaders.

**Comment by Windows10User2** [comment]
> > > 
> > 
> > 
> > Does XEB+ neutrino Launcher Plugin always include Neutrino's latest stable version, and if so, does it include its latest commit as well? Also, what's the difference between Neutrino's latest stable versions and latest development builds? Are the latter more compatible with PS2 games or have extra features?
> 
> The plugin is designed around the stable build of neutrino and as such the latest stable release is included. Commits are changes to made to the public source code, but they do not necessarily correspond to a release. GitHub automatically packages the current version of the source code for distribution with each release at the time it is created. This way the source paired with each release will (at least in theory) result in the same binary as what's pre-compiled in the release. The neutrino development build is compiled from the current version of the source code every time there's a change in the codebase. These releases can happen as often as once per day and undergo minimal testing, if any. This is far too unstable to build a front-end around.
> 
> > What is the List Builder for?
> 
> The list builder is used to generate the game lists required by the HDD, USB, and MX4SIO loaders.

The part regarding commits is very confusing but I guess I should only download a GitHub program if a new release is released because that way it would be very annoying having to always update a program every time a commit was released even if it changed the source code.

I guess even though XEB+ must be run from an USB device, games may be located in it, on the HDD or on a microSD card if using MX4SIO, hence the name of the devices. Also, may games be located in the same USB where XEB+ is located or they have to be located in another one?

**Comment by sync-on-luma** [comment]
> Also, may games be located in the same USB where XEB+ is located or they have to be located in another one?

They have to be located on the same drive. The PS2 can only mount one USB device at a time.
