### ISSUE TITLE
ZSO file support

### ISSUE THREAD

**Issue by teotliv** [sync-on-luma/xebplus-neutrino-loader-plugin#8]
Thank you for keeping the PS2 scene alive! I wanted to ask if you have any plans to add support for ZSO files in the future, in addition to ISO support. It would be a great feature for those of us looking to save some space while still enjoying our games.

**Comment by sync-on-luma** [comment]
That's a change that would need to be added to neutrino, this is just a frontend for it. As far as I'm aware, that's never going to happen because it would add bloat and potentially reduce compatibility.
